opencost:
  prometheus:
    internal:
      serviceName: vmselect-vmks-victoria-metrics-k8s-stack
      namespaceName: vmks
      port: 8481
      path: "/select/0/prometheus"
      scheme: http
  customPricing:
    enabled: true
    costModel:  
      LBIngressDataCost: "0.01"
      FirstFiveForwardingRulesCost: "0.0"
      AdditionalForwardingRuleCost: "0.0"
  ui:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
      - host: opencost.apatsev.org.ru
        paths:
        - /
