nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterName: "cluster.local"

prometheus:
  internal:
    
    enabled: true
    
    serviceName: vmselect-vmks-victoria-metrics-k8s-stack
    
    namespaceName: vmks
    
    port: 8481
    
    path: "/select/0/prometheus"
    
    scheme: http

ui:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: opencost.apatsev.org.ru
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: opencost-tls
        hosts:
          - opencost.apatsev.org.ru

exporter:
  image:
    tag: "1.118.0@sha256:c1a08767fe3c3b2964a75885c145bae0cba32225c0b4c1e0382a77566aef93e9"
  resources:
    requests:
      cpu: '10m'
      memory: '55Mi'
    limits:
      memory: '1Gi'

service:
  type: ClusterIP
  annotations: {}

rbac:
  enabled: true